name: Package Manager Matrix

on:
  workflow_dispatch:

jobs:
  npm-matrix:
    name: npm testing on ${{ matrix.os }} with Node ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false  # Need results from all OS/Node.js combinations
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest, macos-latest]
        node-version: ['18', '20', '22']  # Use specific versions without .x

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'sample-projects/basic-npm/package-lock.json'

      - name: Verify npm installation
        run: |
          node --version
          npm --version
          npm config list

      - name: Generate package-lock.json if missing
        working-directory: sample-projects/basic-npm
        run: |
          if [ ! -f package-lock.json ]; then
            echo "Generating package-lock.json..."
            npm install
          fi
        shell: bash

      - name: Install dependencies with npm
        working-directory: sample-projects/basic-npm
        run: |
          echo "=== Installing dependencies (cache miss/hit test) ==="
          npm ci

      - name: Build project
        working-directory: sample-projects/basic-npm
        run: |
          echo "=== Building project ==="
          npm run build

      - name: Run tests
        working-directory: sample-projects/basic-npm
        run: |
          echo "=== Running tests ==="
          npm run test

      - name: Test cache effectiveness
        working-directory: sample-projects/basic-npm
        run: |
          rm -rf node_modules
          echo "=== Second installation (cache hit expected) ==="
          time npm ci
        shell: bash

  yarn-matrix:
    name: yarn testing on ${{ matrix.os }} with Node ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
  
    strategy:
      fail-fast: false  # Need results from all OS/Node.js combinations
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: ['18', '20', '22']  # Use specific versions without .x
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: 'sample-projects/typescript-yarn/yarn.lock'

      - name: Enable Corepack
        run: corepack enable
          
      - name: Install Yarn via Corepack
        working-directory: sample-projects/typescript-yarn
        run: corepack install
  
      - name: Verify yarn installation
        run: |
          node --version
          yarn --version
  
      - name: Generate or update yarn.lock if needed
        working-directory: sample-projects/typescript-yarn
        run: |
          if [ ! -f yarn.lock ]; then
            echo "No yarn.lock found, generating..."
            yarn install
          else
            echo "yarn.lock exists, checking compatibility..."
            # Try to install with immutable first, fallback to regular install if needed
            yarn install --immutable || yarn install
          fi
        shell: bash
  
      - name: Install dependencies with yarn (first run - cache miss expected)
        working-directory: sample-projects/typescript-yarn
        run: |
          echo "=== First installation (cache miss expected) ==="
          yarn install --immutable
  
      - name: Build TypeScript project
        working-directory: sample-projects/typescript-yarn
        run: |
          echo "=== Building TypeScript project ==="
          yarn build
  
      - name: Run tests
        working-directory: sample-projects/typescript-yarn
        run: |
          echo "=== Running tests ==="
          yarn test
  
      - name: Test TypeScript compilation (type checking)
        working-directory: sample-projects/typescript-yarn
        run: |
          echo "=== TypeScript type checking ==="
          yarn tsc --noEmit
  
      - name: Clear and reinstall (test cache effectiveness)
        working-directory: sample-projects/typescript-yarn
        run: |
          rm -rf node_modules
          echo "=== Second installation (cache hit expected) ==="
          yarn install --immutable
        shell: bash
  
      - name: Verify cache effectiveness
        working-directory: sample-projects/typescript-yarn
        run: |
          echo "=== Yarn cache information ==="
          yarn config get cacheFolder
          echo "=== Installation completed successfully ==="

  pnpm-matrix:
    name: pnpm testing on ${{ matrix.os }} with Node ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false  # Need results from all OS/Node.js combinations
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: ['18', '20', '22']  # Use specific versions without .x

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: 'sample-projects/esm-pnpm/pnpm-lock.yaml'

      - name: Enable Corepack and install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Verify pnpm installation
        run: |
          node --version
          pnpm --version

      - name: Generate pnpm-lock.yaml if missing
        working-directory: sample-projects/esm-pnpm
        run: |
          if [ ! -f pnpm-lock.yaml ]; then
            echo "Generating pnpm-lock.yaml..."
            pnpm install
          fi
        shell: bash

      - name: Install dependencies with pnpm
        working-directory: sample-projects/esm-pnpm
        run: |
          echo "=== Installing dependencies (cache miss/hit test) ==="
          pnpm install --frozen-lockfile

      - name: Build project
        working-directory: sample-projects/esm-pnpm
        run: |
          echo "=== Building project ==="
          pnpm build

      - name: Run tests
        working-directory: sample-projects/esm-pnpm
        run: |
          echo "=== Running tests ==="
          pnpm test

      - name: Test ESM functionality
        working-directory: sample-projects/esm-pnpm
        run: |
          echo "=== Testing ESM functionality ==="
          pnpm start

      - name: Test cache effectiveness
        working-directory: sample-projects/esm-pnpm
        run: |
          rm -rf node_modules
          echo "=== Second installation (cache hit expected) ==="
          time pnpm install --frozen-lockfile
        shell: bash

  package-manager-comparison:
    name: Package manager feature comparison
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use specific version without .x

      - name: Enable Corepack and install package managers
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          corepack prepare pnpm@latest --activate
          echo "Package manager versions:"
          npm --version
          yarn --version
          pnpm --version

      - name: Test npm lockfile handling
        working-directory: sample-projects/basic-npm
        run: |
          rm -f package-lock.json
          npm install
          echo "npm lockfile created:"
          ls -la package-lock.json

      - name: Test yarn lockfile handling
        working-directory: sample-projects/typescript-yarn
        run: |
          rm -f yarn.lock
          yarn install
          echo "yarn lockfile created:"
          ls -la yarn.lock

      - name: Test pnpm lockfile handling
        working-directory: sample-projects/esm-pnpm
        run: |
          rm -f pnpm-lock.yaml
          pnpm install
          echo "pnpm lockfile created:"
          ls -la pnpm-lock.yaml

      - name: Compare installation speed
        run: |
          echo "Comparing package manager installation speeds..."
          echo "npm install speed:"
          cd sample-projects/basic-npm
          rm -rf node_modules
          time npm ci
          echo "yarn install speed:"
          cd ../typescript-yarn
          rm -rf node_modules
          time yarn install --immutable
          echo "pnpm install speed:"
          cd ../esm-pnpm
          rm -rf node_modules
          time pnpm install --frozen-lockfile

  workspace-monorepo-test:
    name: Test monorepo workspace functionality
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use specific version without .x
          cache: 'npm'
          cache-dependency-path: 'sample-projects/monorepo/package-lock.json'

      - name: Generate package-lock.json if missing
        working-directory: sample-projects/monorepo
        run: |
          if [ ! -f package-lock.json ]; then
            echo "Generating package-lock.json for monorepo..."
            npm install
          fi
        shell: bash

      - name: Install dependencies for monorepo
        working-directory: sample-projects/monorepo
        run: |
          echo "=== Installing monorepo dependencies ==="
          npm ci

      - name: Test workspace packages
        working-directory: sample-projects/monorepo
        run: |
          echo "=== Testing workspace packages ==="
          npm run test --workspace=package-a
          npm run test --workspace=package-b
          npm run build --workspaces

      - name: Test cross-package dependencies
        working-directory: sample-projects/monorepo
        run: |
          echo "=== Testing cross-package dependencies ==="
          npm run start --workspace=package-b

  registry-authentication:
    name: Test package registry configurations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test npm registry configuration
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use specific version without .x
          registry-url: 'https://registry.npmjs.org/'

      - name: Verify npm registry
        run: |
          npm config get registry
          echo "Registry configuration verified"

      - name: Test scoped registry configuration
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use specific version without .x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@octocat'

      - name: Verify scoped registry
        run: |
          npm config get @octocat:registry
          echo "Scoped registry configuration verified"

  package-resolution:
    name: Test package resolution strategies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use specific version without .x

      - name: Install package managers via Corepack
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          corepack prepare pnpm@latest --activate

      - name: Install dependencies for all projects
        run: |
          cd sample-projects/basic-npm && npm ci
          cd ../typescript-yarn && yarn install --immutable
          cd ../esm-pnpm && pnpm install --frozen-lockfile

      - name: Test npm resolution
        working-directory: sample-projects/basic-npm
        run: |
          echo "=== NPM Package Resolution ==="
          npm ls
          npm explain lodash || echo "lodash not found in npm project"

      - name: Test yarn resolution
        working-directory: sample-projects/typescript-yarn
        run: |
          echo "=== Yarn Package Resolution ==="
          yarn list
          yarn why typescript

      - name: Test pnpm resolution
        working-directory: sample-projects/esm-pnpm
        run: |
          echo "=== PNPM Package Resolution ==="
          pnpm list
          pnpm why lodash || echo "lodash not found in pnpm project"
